// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCotdyaZIz1nHXgLqPWSIX8lt2erKeR8Xc',
    appId: '1:949939380299:web:a61dd758759bd2da3d2dce',
    messagingSenderId: '949939380299',
    projectId: 'mollery-63499',
    authDomain: 'mollery-63499.firebaseapp.com',
    databaseURL: 'https://mollery-63499-default-rtdb.firebaseio.com',
    storageBucket: 'mollery-63499.appspot.com',
    measurementId: 'G-KDLQKE6KC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTiUxtHJF9KPxDP1-fnpnyxzhJg93ELq4',
    appId: '1:949939380299:android:3e20db750efd49b73d2dce',
    messagingSenderId: '949939380299',
    projectId: 'mollery-63499',
    databaseURL: 'https://mollery-63499-default-rtdb.firebaseio.com',
    storageBucket: 'mollery-63499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmeiV4qx6GDYT1DnnvUbwQc5aYB8_R6mI',
    appId: '1:949939380299:ios:57e2c7bdc6478f393d2dce',
    messagingSenderId: '949939380299',
    projectId: 'mollery-63499',
    databaseURL: 'https://mollery-63499-default-rtdb.firebaseio.com',
    storageBucket: 'mollery-63499.appspot.com',
    androidClientId: '949939380299-1h2dd287fe3bcgt2971cprvr3n1m3lpu.apps.googleusercontent.com',
    iosClientId: '949939380299-odrf6h26b7ki8k8fe2ni72je0drj1a73.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesflut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmeiV4qx6GDYT1DnnvUbwQc5aYB8_R6mI',
    appId: '1:949939380299:ios:a39a284d998c27b03d2dce',
    messagingSenderId: '949939380299',
    projectId: 'mollery-63499',
    databaseURL: 'https://mollery-63499-default-rtdb.firebaseio.com',
    storageBucket: 'mollery-63499.appspot.com',
    androidClientId: '949939380299-1h2dd287fe3bcgt2971cprvr3n1m3lpu.apps.googleusercontent.com',
    iosClientId: '949939380299-994f6cca9229epq97t8s8smhbnnlabgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesflut.RunnerTests',
  );
}
